// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wireinject

import (
	"github.com/RRRHAN/IFYNTH-STORE/back-end/database"
	"github.com/RRRHAN/IFYNTH-STORE/back-end/domains/product"
	"github.com/RRRHAN/IFYNTH-STORE/back-end/domains/cart"
	"github.com/RRRHAN/IFYNTH-STORE/back-end/domains/user"
	"github.com/RRRHAN/IFYNTH-STORE/back-end/middlewares"
	"github.com/RRRHAN/IFYNTH-STORE/back-end/routes"
	"github.com/RRRHAN/IFYNTH-STORE/back-end/utils/config"
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
)

import (
	_ "github.com/google/subcommands"
)

// Injectors from wire.go:

func initializeDependency(config2 *config.Config) (*routes.Dependency, error) {
	db, err := database.NewDB(config2)
	if err != nil {
		return nil, err
	}
	
	// Create the services and handlers
	userService := user.NewService(config2, db)
	middlewaresMiddleware := middlewares.NewMiddlewares(config2, userService)
	validate := validator.New()

	// Handlers
	userHandler := user.NewHandler(userService, validate)
	productService := product.NewService(config2, db)
	productHandler := product.NewHandler(productService, validate)
	cartService := cart.NewService(config2, db)
	cartHandler := cart.NewCartHandler(cartService, validate)

	// Inject into routes
	dependency := routes.NewDependency(config2, middlewaresMiddleware, db, userHandler, productHandler, cartHandler)
	return dependency, nil
}

// wire.go:

var userSet = wire.NewSet(user.NewService, user.NewHandler)

var productSet = wire.NewSet(product.NewService, product.NewHandler)
