version: '3.8'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - webproxy

  nginx-letsencrypt:
    image: nginxproxy/acme-companion
    container_name: nginx_proxy_acme
    restart: unless-stopped
    depends_on:
      - nginx-proxy
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=your@email.com
    networks:
      - webproxy

  app:
    build: ./front-end
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./front-end:/var/www
    env_file:
      - .env
    expose:
      - "9000"
    environment:
      - VIRTUAL_HOST=ifynth.raihan-firm.com
      - LETSENCRYPT_HOST=ifynth.raihan-firm.com
      - LETSENCRYPT_EMAIL=your@email.com
    networks:
      - webproxy

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    volumes:
      - ./front-end:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    depends_on:
      - app
    networks:
      - webproxy

  back-end:
    build: ./back-end
    container_name: golang_backend
    working_dir: /app
    expose:
      - "7777"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - /root/IFYNTH-STORE/back-end/uploads:/app/uploads
    networks:
      - webproxy

  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - webproxy

volumes:
  postgres_data:

networks:
  webproxy:
    external: false
