version: '3.8'

services:
  app:
    build: ./front-end
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./front-end:/var/www
    env_file:
      - .env
    ports:
      - "9000:9000"

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./front-end:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app

  back-end:
    build: ./back-end
    container_name: golang_backend
    working_dir: /app
    ports:
      - "7777:7777"
    depends_on:
      - db
      - ai
    env_file:
      - .env
    volumes:
      - /root/IFYNTH-STORE/back-end/uploads:/app/uploads:/app/uploads

  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
  
  ai:
    build: ./ai
    container_name: ai
    working_dir: /app
    ports:
      - "5000:5000"
    env_file:
      - .env

volumes:
  postgres_data:
