ALTER TABLE carts
ADD CONSTRAINT fk_user
FOREIGN KEY (user_id)
REFERENCES customer(id)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE cart_items
ADD CONSTRAINT fk_product
FOREIGN KEY (product_id)
REFERENCES product(id)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE message
ADD COLUMN admin_id UUID,
ADD COLUMN customer_id UUID;

UPDATE message
SET customer_id = user_id
WHERE role = 'CUSTOMER';

UPDATE message
SET admin_id = user_id
WHERE role = 'ADMIN';

ALTER TABLE message
DROP COLUMN user_id;

ALTER TABLE message
ADD CONSTRAINT fk_customer
FOREIGN KEY (customer_id)
REFERENCES customer(id)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE message
ADD CONSTRAINT fk_admin
FOREIGN KEY (admin_id)
REFERENCES admin(id)
ON DELETE CASCADE
ON UPDATE CASCADE;