ALTER TABLE carts
ADD CONSTRAINT fk_user
FOREIGN KEY (user_id)
REFERENCES customer(id)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE cart_items
ADD CONSTRAINT fk_product
FOREIGN KEY (product_id)
REFERENCES product(id)
ON DELETE CASCADE
ON UPDATE CASCADE;

-- TODO: use different column
ALTER TABLE message
ADD CONSTRAINT fk_customer
FOREIGN KEY (user_id)
REFERENCES customer(id)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE message
ADD CONSTRAINT fk_admin
FOREIGN KEY (user_id)
REFERENCES admin(id)
ON DELETE CASCADE
ON UPDATE CASCADE;