name: Deploy to VPS

on:
  workflow_dispatch:
    inputs:
      no_cache:
        description: 'Build without cache?'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd IFYNTH-STORE
            git pull
            if [ "${{ github.event.inputs.no_cache }}" = "true" ]; then
              docker-compose build --no-cache
            else
              docker-compose build
            fi
            docker-compose up -d
